In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/edtech_reviews.csv")

In [3]:
df.shape

(38000, 15)

In [4]:
df.columns

Index(['platform', 'category', 'source', 'review_id', 'rating', 'review',
       'review_date', 'thumbs_up', 'app_version', 'reply_content',
       'replied_at', 'review_length', 'review_year', 'review_month',
       'rating_category'],
      dtype='str')

In [5]:
df.head()

,platform,category,source,review_id,rating,review,review_date,thumbs_up,app_version,reply_content,replied_at,review_length,review_year,review_month,rating_category
0,Coursera,MOOC,Google Play,d43c2954-87a9-4c88-9753-c35feb505ef0,1,I was excited to enroll in this program. I sig...,2026-07-15 02:45:09,0,6.7.1,NaN,NaN,307.0,2026,July,Very Poor
1,Coursera,MOOC,Google Play,3d82399b-4d3d-46d2-9373-109a8b19e55d,2,Please do not block your app on alternate OSes...,2026-07-14 20:19:06,0,NaN,NaN,NaN,63.0,2026,July,Poor
2,Coursera,MOOC,Google Play,694b2fdc-0a9e-4d55-9eab-295de0affddf,5,This is a best app to learn any course,2026-07-14 18:55:43,0,6.7.1,NaN,NaN,38.0,2026,July,Excellent
3,Coursera,MOOC,Google Play,f779f734-a669-4da8-aeeb-0210bad34df4,1,not able to submit my assignment and do not kn...,2026-07-14 12:29:18,0,6.6.0,NaN,NaN,53.0,2026,July,Very Poor
4,Coursera,MOOC,Google Play,6007ea9a-4045-4276-b681-237211fb822d,3,"I like the Download option, but those Question...",2026-07-14 05:06:54,0,6.7.1,NaN,NaN,293.0,2026,July,Average

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 38000 entries, 0 to 37999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   platform         38000 non-null  str
 1   category         38000 non-null  str
 2   source           38000 non-null  str
 3   review_id        38000 non-null  str
 4   rating           38000 non-null  int64
 5   review           37999 non-null  str
 6   review_date      38000 non-null  str
 7   thumbs_up        38000 non-null  int64
 8   app_version      30928 non-null  str
 9   reply_content    9036 non-null   str
 10  replied_at       9036 non-null   str
 11  review_length    37999 non-null  float64
 12  review_year      38000 non-null  int64
 13  review_month     38000 non-null  str
 14  rating_category  38000 non-null  str
dtypes: float64(1), int64(3), str(11)
memory usage: 4.3 MB

In [7]:

df.describe()

             rating     thumbs_up  review_length   review_year
count  38000.000000  38000.000000   37999.000000  38000.000000
mean       3.869237      1.463395      82.987579   2024.973947
std        1.611079     11.269056     109.902073      2.098600
min        1.000000      0.000000       1.000000   2016.000000
25%        3.000000      0.000000      14.000000   2025.000000
50%        5.000000      0.000000      38.000000   2026.000000
75%        5.000000      1.000000     102.000000   2026.000000
max        5.000000    573.000000    1151.000000   2026.000000

In [8]:
# Missing Values Analysis

df.isnull().sum()

platform               0
category               0
source                 0
review_id              0
rating                 0
review                 1
review_date            0
thumbs_up              0
app_version         7072
reply_content      28964
replied_at         28964
review_length          1
review_year            0
review_month           0
rating_category        0
dtype: int64

In [9]:
df = df.dropna(subset=["review"])

In [10]:
df.isnull().sum()

platform               0
category               0
source                 0
review_id              0
rating                 0
review                 0
review_date            0
thumbs_up              0
app_version         7072
reply_content      28963
replied_at         28963
review_length          0
review_year            0
review_month           0
rating_category        0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)