# Feature Engineering

## Business Objective

The objective of this notebook is to create meaningful features from the cleaned customer review dataset.

These engineered features will improve business analysis, SQL reporting, and Power BI dashboard development.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/processed/cleaned_edtech_reviews.csv")

In [3]:
df.head()

,platform,category,source,review_id,rating,review,review_date,thumbs_up,app_version,reply_content,replied_at,review_length,review_year,review_month,rating_category
0,Coursera,MOOC,Google Play,d43c2954-87a9-4c88-9753-c35feb505ef0,1,I was excited to enroll in this program. I sig...,2026-07-15 02:45:09,0,6.7.1,NaN,NaN,307.0,2026,July,Very Poor
1,Coursera,MOOC,Google Play,3d82399b-4d3d-46d2-9373-109a8b19e55d,2,Please do not block your app on alternate OSes...,2026-07-14 20:19:06,0,NaN,NaN,NaN,63.0,2026,July,Poor
2,Coursera,MOOC,Google Play,694b2fdc-0a9e-4d55-9eab-295de0affddf,5,This is a best app to learn any course,2026-07-14 18:55:43,0,6.7.1,NaN,NaN,38.0,2026,July,Excellent
3,Coursera,MOOC,Google Play,f779f734-a669-4da8-aeeb-0210bad34df4,1,not able to submit my assignment and do not kn...,2026-07-14 12:29:18,0,6.6.0,NaN,NaN,53.0,2026,July,Very Poor
4,Coursera,MOOC,Google Play,6007ea9a-4045-4276-b681-237211fb822d,3,"I like the Download option, but those Question...",2026-07-14 05:06:54,0,6.7.1,NaN,NaN,293.0,2026,July,Average

# Feature 1

## Review Length Category

In [4]:
df["review_length_category"] = pd.cut(
    df["review_length"],
    bins=[0,50,150,float("inf")],
    labels=["Short","Medium","Long"]
)

df[
    ["review_length","review_length_category"]
].head()

   review_length review_length_category
0          307.0                   Long
1           63.0                 Medium
2           38.0                  Short
3           53.0                 Medium
4          293.0                   Long

# Feature 2

## Customer Sentiment

In [5]:
def sentiment(rating):

    if rating <= 2:
        return "Negative"

    elif rating == 3:
        return "Neutral"

    else:
        return "Positive"


df["sentiment"] = df["rating"].apply(sentiment)

df[
    ["rating","sentiment"]
].head()

   rating sentiment
0       1  Negative
1       2  Negative
2       5  Positive
3       1  Negative
4       3   Neutral

# Feature 3

## Review Quarter

In [6]:
quarter_map = {

    "January":"Q1",
    "February":"Q1",
    "March":"Q1",

    "April":"Q2",
    "May":"Q2",
    "June":"Q2",

    "July":"Q3",
    "August":"Q3",
    "September":"Q3",

    "October":"Q4",
    "November":"Q4",
    "December":"Q4"

}

df["review_quarter"] = (
    df["review_month"]
      .map(quarter_map)
)

df[
    ["review_month","review_quarter"]
].head()

  review_month review_quarter
0         July             Q3
1         July             Q3
2         July             Q3
3         July             Q3
4         July             Q3

# Feature 4

## Helpful Review Flag

In [7]:
df["helpful_review"] = (
    df["thumbs_up"] >= 5
)

df[
    ["thumbs_up","helpful_review"]
].head()

   thumbs_up  helpful_review
0          0           False
1          0           False
2          0           False
3          0           False
4          0           False

# Feature 5

## Review Type

In [8]:
def review_type(length):

    if length < 50:
        return "Quick Feedback"

    elif length < 150:
        return "Detailed Review"

    else:
        return "Comprehensive Feedback"


df["review_type"] = (
    df["review_length"]
      .apply(review_type)
)

df[
    ["review_length","review_type"]
].head()

   review_length             review_type
0          307.0  Comprehensive Feedback
1           63.0         Detailed Review
2           38.0          Quick Feedback
3           53.0         Detailed Review
4          293.0  Comprehensive Feedback

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37999 entries, 0 to 37998
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   platform                37999 non-null  str
 1   category                37999 non-null  str
 2   source                  37999 non-null  str
 3   review_id               37999 non-null  str
 4   rating                  37999 non-null  int64
 5   review                  37999 non-null  str
 6   review_date             37999 non-null  str
 7   thumbs_up               37999 non-null  int64
 8   app_version             30927 non-null  str
 9   reply_content           9036 non-null   str
 10  replied_at              9036 non-null   str
 11  review_length           37999 non-null  float64
 12  review_year             37999 non-null  int64
 13  review_month            37999 non-null  str
 14  rating_category         37999 non-null  str
 15  review_length_category  37999 non-null  category
 16  sentiment               37999 non-null  str
 17  review_quarter          37999 non-null  str
 18  helpful_review          37999 non-null  bool
 19  review_type             37999 non-null  str
dtypes: bool(1), category(1), float64(1), int64(3), str(14)
memory usage: 5.3 MB

In [11]:
df.to_csv(
    "../data/featured/final_edtech_reviews.csv",
    index=False
)

# Feature Engineering Summary

The following engineered features were created:

- Review Length Category
- Customer Sentiment
- Review Quarter
- Helpful Review Flag
- Review Type

The final engineered dataset has been saved for SQL analysis and Power BI dashboard development.